'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bookings
    Public Property id As Integer
    Public Property pilot As Integer
    Public Property plane As Integer
    Public Property [date] As Date
    Public Property duration As System.TimeSpan

    Public Overridable Property Planes As planes
    Public Overridable Property User As users

End Class
