'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class flights
    Public Property id As Integer
    Public Property departureSite As Integer
    Public Property departureDate As Date
    Public Property arrivalSite As Integer
    Public Property arrivalDate As Date
    Public Property plane As Integer
    Public Property duration As Nullable(Of System.TimeSpan)
    Public Property pilot As Integer
    Public Property monoPilot As Integer
    Public Property dayLandings As Nullable(Of Integer)
    Public Property nightLandings As Nullable(Of Integer)

    Public Overridable Property ArrivalField As landingFields
    Public Overridable Property DepartureField As landingFields
    Public Overridable Property User As users
    Public Overridable Property Planes As planes

End Class
