'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class landingFields
    Public Property id As Integer
    Public Property name As String
    Public Property acronym As String

    Public Overridable Property ArrivalFlights As ICollection(Of flights) = New HashSet(Of flights)
    Public Overridable Property DepartureFlights As ICollection(Of flights) = New HashSet(Of flights)
    Public Overridable Property Users As ICollection(Of users) = New HashSet(Of users)
    Public Overridable Property planes As ICollection(Of planes) = New HashSet(Of planes)

End Class
