'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class flightlogappEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=flightlogappEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property bookings() As DbSet(Of bookings)
    Public Overridable Property flights() As DbSet(Of flights)
    Public Overridable Property landingFields() As DbSet(Of landingFields)
    Public Overridable Property planes() As DbSet(Of planes)
    Public Overridable Property users() As DbSet(Of users)
    Public Overridable Property userTypes() As DbSet(Of userTypes)

End Class
