'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class planes
    Public Property id As Integer
    Public Property plate As String
    Public Property owner As Integer
    Public Property model As String
    Public Property landingField As Nullable(Of Integer)

    Public Overridable Property Bookings As ICollection(Of bookings) = New HashSet(Of bookings)
    Public Overridable Property Flights As ICollection(Of flights) = New HashSet(Of flights)
    Public Overridable Property User As users
    Public Overridable Property LandingFields As landingFields

End Class
