'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class users
    Public Property id As Integer
    Public Property username As String
    Public Property password As String
    Public Property userType As Integer
    Public Property landingField As Integer
    Public Property name As String
    Public Property lastname As String
    Public Property image As String

    Public Overridable Property Bookings As ICollection(Of bookings) = New HashSet(Of bookings)
    Public Overridable Property Flights As ICollection(Of flights) = New HashSet(Of flights)
    Public Overridable Property LandingFields As landingFields
    Public Overridable Property Planes As ICollection(Of planes) = New HashSet(Of planes)
    Public Overridable Property UserTypes As userTypes

End Class
